[package]
name = "js-compute-runtime"
version = "0.5.0"
authors = ["Fastly <oss@fastly.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.66"
env_logger = "0.9.3"
log = "0.4.17"
structopt = "0.3.20"
tempfile = "3.1.0"
wizer = "1.4.0"
tree-sitter = "~0.20"
tree-sitter-javascript = "~0.20"
