# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["tartanllama@gmail.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-javascript-empty"
description = ""
language = "javascript"
manifest_version = 3
name = "sy-test"
service_id = ""

[local_server]

[scripts]
build = "node ../js-compute-runtime-cli.js src/index.js"
post_init = "npm install"

[setup]
[setup.backends]
[setup.backends.httpme]
address = "http-me.glitch.me"
port = 443
